### ISSUE TITLE
Calendar Issue

### ISSUE THREAD

**Issue by opus1269** [michalsukupcak/Material-New-Tab#1]
Getting the following error:

``` sh
Uncaught TypeError: Cannot read property 'date' of undefined
```

in the push call here:

``` js
            getEventsRequestResponse: function (event) {
                var events = event.detail.response.items;
                for (var i = 0; i < events.length; i++) {
                    var e = events[i];
                    this.push('events', new Event(e.summary, (e.start.date != null ? e.start.date : e.start.dateTime), event.detail.response.summary, e.htmlLink));
                }
                if (this.calendarIndex < this.calendars.length) {
                    this.fireGetEventsRequest();
                } else {
                    this.events.sort(__compareEvents);
                    this.events = this.events.slice();
                    this.$.eventsLocalstorage.save();
                    this.lastUpdate = moment().unix();
                    this.loading = false;
                }
            },
```

The calendar event looks like this (XXX added)

``` sh
etag: ""XXX""
id: "XXX"
kind: "calendar#event"
originalStartTime: Object
recurringEventId: "XXX"
status: "cancelled"
__proto__: Object
```

Apparently, cancelled events are still hanging around and they don't have a start property.

Symptoms are the spinner doesn't hide on the calendar and the Bookmarks never get processed.

**Comment by michalsukupcak** [comment]
Hello,

Unfortunately I can't publish a hotfix right now since Polymer and its build tools have evolved a lot in the last couple of months and I would have to rewrite a lot of the extension in order to get a working build with updated tools.

However I'm currently working on new version of the extension based on PSK 1.2.1 and I will definitely fix this issue. I hope to get it done by January 2016, depending on how much time I will have.

Until then I would ask you for patience and as a workaround suggest deleting cancelled events from your calendar (and maybe clear local storage under F12 -> Resources -> Local storage -> Key: material-new-tab-calendar-events, if necessary). I know its not a convenient solution, but I can't help you more right now.

However, thank you very much for amazingly well documented and reported issue! :)

**Comment by michalsukupcak** [comment]
Hello,

Sorry for the super long wait for a response. The extension has undertaken a significant revamp and this issue is no longer relevant.
